import Link from "next/link";
import { ArrowRight, CalendarCheck2, CalendarClock, Clock3, Contact, DollarSign, Scissors, TrendingUp, UserPlus, UsersRound, WalletCards } from "lucide-react";
import { AnalyticsCharts } from "@/components/analytics-charts";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { requireUser } from "@/lib/auth";
import { customerName, formatMoney } from "@/lib/format";
import { formatBusinessDate } from "@/lib/time";
import { getDashboardData } from "@/server/analytics";

export default async function DashboardPage() {
  const user = await requireUser(); const locale = user.settings?.locale || "en"; const currency = user.settings?.currency || "CAD"; const timezone = user.settings?.timezone || "America/Toronto";
  const data = await getDashboardData(timezone);
  const cards = [
    ["Today's appointments", data.kpis.todayCount, CalendarCheck2], ["This week", data.kpis.weekCount, TrendingUp], ["Customers", data.kpis.customerCount, Contact], ["Returning customers", data.kpis.returningCustomers, UsersRound],
    ["Finalized revenue · month", formatMoney(data.kpis.monthRevenue,currency,locale), DollarSign], ["Finalized revenue · year", formatMoney(data.kpis.yearRevenue,currency,locale), WalletCards], ["Finalized outstanding", formatMoney(data.kpis.outstanding,currency,locale), DollarSign], ["Finalized hours · month", `${data.kpis.hours.toFixed(1)}h`, Clock3], ["Actual hourly income", formatMoney(data.kpis.hourlyIncome,currency,locale), TrendingUp],
  ] as const;
  return <><PageHeading title={locale === "fa" ? "داشبورد" : "Dashboard"} description={locale === "fa" ? `خوش آمدید، ${user.name}` : `Welcome back, ${user.name}. Income and hours below use finalized appointments only.`} actions={<><Link className="quick-action" href="/customers/new"><span><UserPlus size={16}/></span>Customer</Link><Link className="quick-action" href="/services/new"><span><Scissors size={16}/></span>Service</Link></>}/><div className="grid grid-cols-2 gap-2.5 sm:gap-3 xl:grid-cols-3 2xl:grid-cols-5">{cards.map(([label,value,Icon]) => <article className="stat" key={label}><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium leading-5 text-slate-400 sm:text-sm">{label}</p><Icon size={17} className="shrink-0 text-teal-300/75 sm:size-[18px]"/></div><p className="mt-3 text-xl font-semibold tracking-[-0.03em] text-white sm:mt-4 sm:text-2xl">{value}</p></article>)}</div><div className="mt-5"><AnalyticsCharts revenue={data.revenueByMonth} services={data.serviceRevenue}/></div><section className="panel mt-5 overflow-hidden"><div className="panel-header"><div className="flex min-w-0 items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl border border-sky-300/15 bg-sky-300/8 text-sky-300"><CalendarClock size={17}/></span><div className="min-w-0"><h2 className="truncate font-semibold text-white">Upcoming appointments</h2><p className="mt-0.5 truncate text-xs text-slate-400">Scheduled and confirmed studio visits</p></div></div><Link href="/appointments?stage=scheduled" className="button-secondary h-9 min-h-9 shrink-0 px-3">View <ArrowRight size={14}/></Link></div>{data.upcoming.length ? <div className="divide-y divide-white/9">{data.upcoming.map((item) => <Link href={`/appointments/${item.id}`} key={item.id} className="flex items-center justify-between gap-3 px-5 py-4 transition hover:bg-white/[0.035] sm:px-6"><div className="min-w-0"><p className="truncate font-medium text-slate-100" dir="auto">{customerName(item.customer)}</p><p className="mt-1 truncate text-sm text-slate-400" dir="auto">{item.serviceNameSnapshot} · {formatBusinessDate(item.startAt,locale,timezone)}</p></div><StatusBadge status={item.status}/></Link>)}</div> : <div className="empty">No upcoming appointments.</div>}</section></>;
}
