import { Save } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { requireBusinessPermission } from "@/lib/auth";
import { updateSettings } from "@/server/actions/settings";

export default async function BusinessSettingsPage() {
  const user = await requireBusinessPermission("business.manage");
  const settings = user.settings;
  return <><PageHeading backHref="/settings" title="Studio profile & appearance"/><form action={updateSettings} className="panel max-w-3xl p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label" htmlFor="businessName">Business name</label><input className="field" id="businessName" name="businessName" defaultValue={settings?.businessName || "Manisa"}/></div><div><label className="label" htmlFor="locale">Workspace language</label><select className="field" id="locale" name="locale" defaultValue={settings?.locale || "en"}><option value="en">English</option><option value="fa">فارسی</option></select></div><div id="appearance"><label className="label" htmlFor="theme">Appearance</label><select className="field" id="theme" name="theme" defaultValue={settings?.theme || "DARK"}><option value="DARK">Dark</option><option value="LIGHT">Light</option><option value="SYSTEM">System</option></select></div><div><label className="label" htmlFor="currency">Currency</label><select className="field" id="currency" name="currency" defaultValue={settings?.currency || "CAD"}><option>CAD</option><option>USD</option></select></div><div><label className="label">Business timezone</label><input className="field opacity-70" value={settings?.timezone || "America/Toronto"} readOnly/></div><div className="sm:col-span-2 border-t border-white/8 pt-5"><h2 className="font-semibold">Public studio page</h2></div><div className="sm:col-span-2"><label className="label" htmlFor="studioTagline">Tagline</label><input className="field" dir="auto" id="studioTagline" maxLength={160} name="studioTagline" defaultValue={settings?.studioTagline || ""}/></div><div className="sm:col-span-2"><label className="label" htmlFor="studioBiography">Short biography</label><textarea className="field min-h-28 resize-y" dir="auto" id="studioBiography" maxLength={1200} name="studioBiography" defaultValue={settings?.studioBiography || ""}/></div><div><label className="label" htmlFor="publicPhone">Public phone</label><input className="field" dir="ltr" id="publicPhone" name="publicPhone" defaultValue={settings?.publicPhone || ""}/></div><div><label className="label" htmlFor="publicEmail">Public email</label><input className="field" dir="ltr" id="publicEmail" name="publicEmail" type="email" defaultValue={settings?.publicEmail || ""}/></div><div className="sm:col-span-2"><label className="label" htmlFor="bookingUrl">Booking URL</label><input className="field" dir="ltr" id="bookingUrl" name="bookingUrl" type="url" defaultValue={settings?.bookingUrl || ""}/></div></div><button className="button mt-7"><Save size={16}/>Save settings</button></form></>;
}
