import Image from "next/image";
import Link from "next/link";
import { after } from "next/server";
import { ArrowUpRight, CalendarDays, Instagram, Mail, MapPin, Phone, Scissors, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
import { CategoryIcon } from "@/components/category-icon";
import { getCurrentUser } from "@/lib/auth";
import { instagramConfigured } from "@/lib/env";
import { instagramCacheIsStale } from "@/lib/instagram-media";
import { prisma } from "@/lib/prisma";
import { syncInstagramConnection } from "@/server/instagram";

const fallbackAddress = process.env.NEXT_PUBLIC_BUSINESS_ADDRESS?.trim() || "Toronto, Ontario";

function safePublicUrl(value: string | null | undefined) {
  if (!value) return "";
  try { const url = new URL(value); return ["http:", "https:"].includes(url.protocol) ? url.toString() : ""; } catch { return ""; }
}

export async function StudioLanding({ slug }: { slug: string }) {
  const studio = await prisma.business.findUnique({ where: { slug }, include: { settings: true } });
  if (!studio?.active || studio.deletedAt) notFound();
  const [user, categories, featuredPhotos, connection] = await Promise.all([
    getCurrentUser(),
    prisma.studioCategory.findMany({ where: { businessId: studio.id, active: true, deletedAt: null, services: { some: { active: true, deletedAt: null } } }, orderBy: [{ position: "asc" }, { name: "asc" }], include: { services: { where: { active: true, deletedAt: null }, orderBy: { name: "asc" }, take: 4, select: { id: true, name: true } }, _count: { select: { services: { where: { active: true, deletedAt: null } } } } } }),
    prisma.mediaAsset.findMany({ where: { businessId: studio.id, deletedAt: null, featuredAt: { not: null }, appointment: { deletedAt: null, status: "COMPLETED" } }, orderBy: { featuredAt: "desc" }, take: 8, select: { id: true } }),
    instagramConfigured() ? prisma.instagramConnection.findUnique({ where: { businessId: studio.id }, select: { id: true, username: true, lastSyncedAt: true, posts: { where: { active: true }, orderBy: { publishedAt: "desc" }, take: 6, select: { id: true, caption: true, permalink: true } } } }) : null,
  ]);
  if (connection && instagramCacheIsStale(connection.lastSyncedAt)) after(() => syncInstagramConnection(connection.id).catch(() => undefined));
  const settings = studio.settings;
  const bookingUrl = safePublicUrl(settings?.bookingUrl);
  const instagramUrl = connection?.username ? `https://www.instagram.com/${connection.username}/` : safePublicUrl(settings?.instagramUrl);
  const phone = settings?.publicPhone?.trim() || "";
  const email = settings?.publicEmail?.trim() || "";
  const primaryHref = bookingUrl || instagramUrl || (phone ? `tel:${phone.replace(/[^+\d]/g, "")}` : email ? `mailto:${email}` : "#contact");
  const primaryLabel = bookingUrl ? "Book an appointment" : instagramUrl ? "Message us on Instagram" : phone ? "Call the studio" : email ? "Email the studio" : "Contact the studio";
  const managementHref = user ? "/report" : "/login";
  const instagramPosts = connection?.posts || [];

  return <main className="min-h-screen overflow-hidden bg-[#f5eee6] text-[#30251f]" dir="ltr" lang="en" data-no-translate>
    <header className="absolute inset-x-0 top-0 z-30"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><a className="flex items-center gap-3 text-white" href="#top"><span className="flex size-10 items-center justify-center rounded-full border border-white/30 bg-black/15 backdrop-blur"><Sparkles size={18}/></span><span className="text-lg font-semibold tracking-wide">{studio.name}</span></a><nav className="hidden gap-7 text-sm text-white/85 md:flex"><a href="#services">Services</a><a href="#work">Our work</a><a href="#studio">The studio</a><a href="#contact">Contact</a></nav><Link className="text-sm font-medium text-white underline decoration-white/35 underline-offset-4" href={managementHref}>Login</Link></div></header>
    <section className="relative min-h-[48rem] bg-[#4b322c]" id="top"><Image alt="Hair stylist working with a client in a warm home studio" className="object-cover object-center" fill priority sizes="100vw" src="/landing/hair-styling.webp"/><div className="absolute inset-0 bg-gradient-to-r from-[#241511]/90 via-[#2b1c17]/60 to-transparent"/><div className="relative mx-auto flex min-h-[48rem] max-w-7xl items-end px-5 pb-20 pt-32 sm:px-8 sm:pb-24 lg:px-10"><div className="max-w-2xl text-white"><p className="mb-5 text-xs font-semibold uppercase tracking-[.28em] text-[#efd6c8]">Private hair & nail studio · Toronto</p><h1 className="font-serif text-5xl leading-[.98] tracking-[-.04em] sm:text-7xl lg:text-[5.6rem]">Beautiful work,<br/>made personal.</h1><p className="mt-7 max-w-xl text-base leading-8 text-white/75 sm:text-lg">{settings?.studioTagline || "Thoughtful hair and nail services in a calm home-studio setting—one appointment, one client, and every detail considered."}</p><div className="mt-9 flex flex-wrap gap-3"><a className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#f4d3c0] px-6 font-semibold text-[#3b251e] transition hover:bg-white" href={primaryHref}>{primaryLabel}<ArrowUpRight size={17}/></a><a className="inline-flex min-h-12 items-center rounded-full border border-white/35 px-6 font-semibold text-white backdrop-blur transition hover:bg-white/10" href="#services">Explore services</a></div></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:py-28" id="studio"><div className="relative mx-auto aspect-[4/5] w-full max-w-lg"><Image alt="Professional manicure detail" className="rounded-[2.5rem] object-cover shadow-[0_35px_90px_rgba(78,51,42,.22)]" fill sizes="(max-width:1024px) 90vw, 42vw" src="/landing/manicure.webp"/><div className="absolute -bottom-5 -right-3 rounded-2xl bg-[#31483c] p-5 text-[#edf3ee] shadow-xl sm:-right-8"><Sparkles size={20}/><p className="mt-3 max-w-36 text-sm leading-6">Quiet appointments.<br/>Careful technique.<br/>Lasting details.</p></div></div><div className="flex flex-col justify-center lg:pl-10"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#9a5d48]">A studio that feels like you</p><h2 className="mt-5 font-serif text-4xl leading-tight tracking-[-.035em] sm:text-6xl">Hair, nails, and time that is truly yours.</h2><p className="mt-7 max-w-xl text-base leading-8 text-[#755f54]">{settings?.studioBiography || "Manisa is an appointment-only home studio for people who value a relaxed atmosphere and work tailored to them. From polished nails to refreshed hair, every visit is unhurried and personal."}</p><div className="mt-8 flex flex-wrap gap-5 text-sm text-[#634d43]"><span className="flex items-center gap-2"><CalendarDays size={17}/>Appointment only</span><span className="flex items-center gap-2"><MapPin size={17}/>{settings?.address || fallbackAddress}</span></div></div></section>
    <section className="bg-[#302a27] py-20 text-[#f8f1eb] lg:py-28" id="services"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#e8bca9]">Services</p><h2 className="mt-5 font-serif text-4xl tracking-[-.035em] sm:text-6xl">Made for real life,<br/>finished beautifully.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] bg-white/15 md:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <article className="bg-[#302a27] p-7 sm:p-8" key={category.id}><span className="flex size-11 items-center justify-center rounded-full bg-white/8 text-[#f1c6b4]"><CategoryIcon name={category.icon} size={20}/></span><h3 className="mt-6 text-xl font-semibold" dir="auto">{category.name}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-white/55" dir="auto">{category.description || `${category._count.services} services available.`}</p><div className="mt-5 space-y-2">{category.services.map((service) => <p className="flex items-center gap-2 text-sm text-white/75" dir="auto" key={service.id}><Scissors className="shrink-0 text-[#d9a995]" size={13}/>{service.name}</p>)}</div></article>)}{!categories.length && <p className="bg-[#302a27] p-10 text-white/60">The studio service menu is being prepared.</p>}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28" id="work"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#9a5d48]">Selected work</p><h2 className="mt-5 font-serif text-4xl tracking-[-.035em] sm:text-6xl">From the studio chair.</h2></div>{instagramUrl && <a className="inline-flex items-center gap-2 text-sm font-semibold" href={instagramUrl} rel="noreferrer" target="_blank"><Instagram size={17}/>Follow the studio<ArrowUpRight size={15}/></a>}</div>{featuredPhotos.length ? <div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{featuredPhotos.map((photo, index) => <div className={`relative overflow-hidden rounded-[1.5rem] bg-[#e2d4ca] ${index === 0 ? "col-span-2 row-span-2" : ""}`} key={photo.id}><div className="aspect-square"><Image alt="Featured studio work" className="object-cover transition duration-500 hover:scale-[1.03]" fill sizes={index === 0 ? "(max-width:768px) 100vw, 50vw" : "(max-width:768px) 50vw, 25vw"} src={`/public-media/gallery/${photo.id}`} unoptimized/></div></div>)}</div> : <div className="mt-10 grid gap-3 sm:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><Image alt="Hair service at Manisa" className="object-cover" fill sizes="50vw" src="/landing/hair-styling.webp"/></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><Image alt="Manicure service at Manisa" className="object-cover" fill sizes="50vw" src="/landing/manicure.webp"/></div></div>}{instagramPosts.length > 0 && <div className="mt-14 grid grid-cols-2 gap-3 md:grid-cols-3">{instagramPosts.map((post) => <a className="group relative aspect-square overflow-hidden rounded-[1.5rem] bg-[#e2d4ca]" href={post.permalink} key={post.id} rel="noreferrer" target="_blank"><Image alt={post.caption || "Manisa Instagram post"} className="object-cover transition duration-500 group-hover:scale-[1.03]" fill sizes="(max-width:768px) 50vw, 33vw" src={`/public-media/instagram/${post.id}`} unoptimized/><span className="absolute right-3 top-3 flex size-9 items-center justify-center rounded-full bg-black/55 text-white backdrop-blur"><Instagram size={16}/></span></a>)}</div>}</section>
    <section className="bg-[#c98268] px-5 py-20 text-[#2d1a14] sm:px-8 lg:py-28" id="contact"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.25em]">Ready when you are</p><h2 className="mt-5 max-w-4xl font-serif text-5xl leading-[1.02] tracking-[-.04em] sm:text-7xl">Let’s plan your next appointment.</h2></div><a className="inline-flex min-h-14 items-center justify-center gap-2 rounded-full bg-[#2d1a14] px-7 font-semibold text-white" href={primaryHref}>{primaryLabel}<ArrowUpRight size={18}/></a></div><div className="mx-auto mt-14 flex max-w-7xl flex-wrap gap-6 border-t border-[#2d1a14]/20 pt-7 text-sm">{phone && <a className="flex items-center gap-2" href={`tel:${phone.replace(/[^+\d]/g, "")}`}><Phone size={16}/>{phone}</a>}{email && <a className="flex items-center gap-2" href={`mailto:${email}`}><Mail size={16}/>{email}</a>}<span className="flex items-center gap-2"><MapPin size={16}/>{settings?.address || fallbackAddress}</span></div></section>
    <footer className="bg-[#211b18] px-5 py-8 text-sm text-white/55 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} {studio.name}</p><div className="flex gap-5"><a href="#services">Services</a><a href="#contact">Contact</a><Link href={managementHref}>Login</Link></div></div></footer>
  </main>;
}

export default async function Home() {
  const [manisaStudio, firstStudio, setupComplete] = await Promise.all([
    prisma.business.findFirst({ where: { slug: "manisa", active: true, deletedAt: null }, select: { slug: true } }),
    prisma.business.findFirst({ where: { active: true, deletedAt: null }, orderBy: { createdAt: "asc" }, select: { slug: true } }),
    prisma.platformAccess.count({ where: { role: "ROOT_OWNER" } }),
  ]);
  const studio = manisaStudio || firstStudio;
  if (studio) return <StudioLanding slug={studio.slug}/>;
  return <main className="flex min-h-screen items-center justify-center bg-[#f5eee6] px-5 text-[#30251f]" dir="ltr" lang="en"><section className="max-w-lg rounded-[2rem] bg-white p-8 text-center shadow-xl"><Sparkles className="mx-auto" size={28}/><h1 className="mt-5 font-serif text-4xl">Set up Manisa</h1><p className="mt-3 leading-7 text-[#755f54]">Create the first system owner and the Manisa business workspace.</p><Link className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#30251f] px-6 font-semibold text-white" href={setupComplete ? "/login" : "/setup"}>{setupComplete ? "Sign in" : "Create system owner"}<ArrowUpRight size={16}/></Link></section></main>;
}
