import Image from "next/image";
import Link from "next/link";
import { after } from "next/server";
import { ArrowRight, CalendarDays, ExternalLink, Instagram, LockKeyhole, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { CategoryIcon } from "@/components/category-icon";
import { getCurrentUser } from "@/lib/auth";
import { instagramConfigured } from "@/lib/env";
import { instagramCacheIsStale } from "@/lib/instagram-media";
import { prisma } from "@/lib/prisma";
import { syncInstagramConnection } from "@/server/instagram";

const business = {
  address: process.env.NEXT_PUBLIC_BUSINESS_ADDRESS?.trim() || "Toronto, Ontario",
  instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL?.trim() || "",
};

export default async function Home() {
  const instagramEnabled = instagramConfigured();
  const [user, categories, featuredPhotos, connection] = await Promise.all([
    getCurrentUser(),
    prisma.studioCategory.findMany({ where: { active: true, deletedAt: null, services: { some: { active: true, deletedAt: null } } }, orderBy: [{ position: "asc" }, { name: "asc" }], include: { services: { where: { active: true, deletedAt: null }, orderBy: { name: "asc" }, take: 5, select: { id: true, name: true } }, _count: { select: { services: { where: { active: true, deletedAt: null } } } } } }),
    prisma.appointmentPhoto.findMany({ where: { deletedAt: null, featuredAt: { not: null }, appointment: { deletedAt: null, status: "COMPLETED", customer: { deletedAt: null } } }, orderBy: { featuredAt: "desc" }, take: 8, select: { id: true } }),
    instagramEnabled ? prisma.instagramConnection.findFirst({ select: { id: true, username: true, lastSyncedAt: true, posts: { where: { active: true }, orderBy: { publishedAt: "desc" }, take: 8, select: { id: true, caption: true, permalink: true, mediaType: true, publishedAt: true } } } }) : null,
  ]);

  if (connection && instagramCacheIsStale(connection.lastSyncedAt)) {
    after(() => syncInstagramConnection(connection.id).catch(() => undefined));
  }
  const instagramPosts = connection?.posts || [];
  const staffHref = user ? "/report" : "/login";
  const staffLabel = user ? "Open management" : "Staff login";

  return <main className="min-h-screen overflow-hidden bg-[#070a10] text-white">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_15%_0%,rgba(37,99,235,.16),transparent_30rem),radial-gradient(circle_at_90%_20%,rgba(30,64,175,.1),transparent_26rem)]"/>
    <header className="relative z-10 border-b border-blue-200/10 bg-[#080c14]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3.5 sm:px-8 lg:px-10"><Link aria-label="Manisa home" className="flex items-center gap-3" href="/"><span className="flex size-10 items-center justify-center rounded-xl border border-blue-300/20 bg-gradient-to-br from-[#19345f] to-[#0c1930] text-blue-200 shadow-[0_10px_30px_rgba(15,49,100,.3)]"><Sparkles size={19}/></span><div><p className="font-semibold tracking-[-.02em]">Manisa</p><p className="text-[11px] text-slate-500">Hair & nail studio</p></div></Link><nav aria-label="Public navigation" className="hidden items-center gap-6 text-sm text-slate-400 md:flex"><a className="hover:text-white" href="#services">Services</a>{featuredPhotos.length > 0 && <a className="hover:text-white" href="#gallery">Gallery</a>}{instagramPosts.length > 0 && <a className="hover:text-white" href="#instagram">Instagram</a>}<a className="hover:text-white" href="#contact">Contact</a></nav><Link className="button-secondary min-h-10" href={staffHref}><LockKeyhole size={15}/><span className="hidden sm:inline">{staffLabel}</span><span className="sm:hidden">Staff</span></Link></div></header>

    <section className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.08fr_.92fr] lg:px-10 lg:pb-28 lg:pt-28"><div className="flex flex-col justify-center"><div className="mb-6 inline-flex w-fit items-center gap-2 rounded-full border border-blue-300/15 bg-blue-400/[0.07] px-3 py-1.5 text-sm font-medium text-blue-200"><Sparkles size={15}/>Beauty, detail and care</div><h1 className="max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-6xl lg:text-7xl">A calm studio for your next look.</h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">Professional hair and nail services with careful detail, personal appointments, and work you can explore before you visit.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a className="button min-h-12 px-5" href="#contact">Contact Manisa<ArrowRight size={16}/></a><a className="button-secondary min-h-12 px-5" href={featuredPhotos.length ? "#gallery" : "#services"}>Explore our work</a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500"><span className="flex items-center gap-2"><CalendarDays className="text-blue-300" size={16}/>Appointment based</span><span className="flex items-center gap-2"><MapPin className="text-blue-300" size={16}/>{business.address}</span></div></div><div className="relative"><div className="absolute inset-8 rounded-full bg-blue-500/10 blur-3xl"/><div className="relative overflow-hidden rounded-[1.8rem] border border-blue-200/12 bg-gradient-to-br from-[#111d31] to-[#090f1a] p-3 shadow-[0_30px_90px_rgba(0,0,0,.4)]"><div className="rounded-[1.35rem] border border-white/8 bg-black/10 p-6 sm:p-8"><div className="flex items-center justify-between border-b border-white/8 pb-6"><div><p className="text-sm font-medium text-blue-300">Manisa studio</p><p className="mt-1 text-2xl font-semibold tracking-[-.04em]">Designed around you</p></div><span className="flex size-12 items-center justify-center rounded-2xl border border-blue-300/15 bg-blue-400/10 text-blue-200"><Sparkles size={23}/></span></div><div className="mt-6 grid gap-3">{[["Personal appointments","Time reserved specifically for your service"],["Modern techniques","Hair, colour, manicure, extensions, and nail design"],["A growing portfolio","Recent studio work selected by Manisa"]].map(([title, copy]) => <div className="rounded-xl border border-white/8 bg-white/[0.02] p-4" key={title}><p className="font-semibold text-slate-100">{title}</p><p className="mt-1 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div></div></div></div></section>

    <section className="relative z-10 border-y border-white/8 bg-white/[0.015]" id="services"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><p className="text-sm font-semibold uppercase tracking-[.18em] text-blue-300">Services</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-3xl font-semibold tracking-[-.045em] sm:text-4xl">Studio categories built around your needs.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-400">Our service menu evolves with the studio. Contact Manisa to confirm exact availability, timing, and pricing.</p></div></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <article className="overflow-hidden rounded-2xl border border-blue-200/10 bg-[#0c121d] p-6 shadow-[0_16px_45px_rgba(0,0,0,.2)]" key={category.id}><span className="flex size-11 items-center justify-center rounded-xl" style={{ backgroundColor: `${category.accentColor}18`, color: category.accentColor }}><CategoryIcon name={category.icon} size={21}/></span><h3 className="mt-5 text-xl font-semibold tracking-[-.03em]">{category.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{category.description || `${category._count.services} studio services available.`}</p><div className="mt-5 flex flex-wrap gap-2">{category.services.map((service) => <span className="rounded-full border border-white/8 bg-white/[0.025] px-2.5 py-1 text-xs text-slate-400" dir="auto" key={service.id}>{service.name}</span>)}{category._count.services > category.services.length && <span className="rounded-full border border-blue-300/10 bg-blue-400/[0.05] px-2.5 py-1 text-xs text-blue-300">+{category._count.services - category.services.length} more</span>}</div></article>)}</div></div></section>

    {featuredPhotos.length > 0 && <section className="relative z-10 mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-24" id="gallery"><p className="text-sm font-semibold uppercase tracking-[.18em] text-blue-300">Featured gallery</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.045em] sm:text-4xl">Work selected by the studio.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-400">A current selection of finalized Manisa work. No private appointment or customer information is published.</p><div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{featuredPhotos.map((photo, index) => <div className={`relative overflow-hidden rounded-2xl border border-blue-200/10 bg-[#0c121d] ${index === 0 ? "col-span-2 row-span-2" : ""}`} key={photo.id}><div className="aspect-square"><Image alt="Featured Manisa studio work" className="object-cover transition duration-500 hover:scale-[1.025]" fill sizes={index === 0 ? "(max-width: 640px) 100vw, 50vw" : "(max-width: 640px) 50vw, 25vw"} src={`/public-media/gallery/${photo.id}`} unoptimized/></div></div>)}</div></section>}

    {instagramPosts.length > 0 && <section className="relative z-10 border-y border-white/8 bg-white/[0.015]" id="instagram"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="flex items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[.18em] text-blue-300"><Instagram size={16}/>Latest posts</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.045em] sm:text-4xl">From Instagram.</h2></div>{(connection?.username || business.instagram) && <a className="button-secondary" href={connection?.username ? `https://www.instagram.com/${connection.username}/` : business.instagram} rel="noreferrer" target="_blank">View profile<ExternalLink size={15}/></a>}</div><div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{instagramPosts.map((post) => <a aria-label={post.caption ? `Instagram: ${post.caption.slice(0, 80)}` : "Open Instagram post"} className="group overflow-hidden rounded-2xl border border-blue-200/10 bg-[#0c121d]" href={post.permalink} key={post.id} rel="noreferrer" target="_blank"><div className="relative aspect-square overflow-hidden"><Image alt="Latest Manisa Instagram post" className="object-cover transition duration-500 group-hover:scale-[1.035]" fill sizes="(max-width: 640px) 50vw, 25vw" src={`/public-media/instagram/${post.id}`} unoptimized/><span className="absolute right-2 top-2 flex size-8 items-center justify-center rounded-full bg-[#08101e]/85 text-blue-200"><Instagram size={15}/></span></div>{post.caption && <p className="line-clamp-2 p-3 text-xs leading-5 text-slate-400" dir="auto">{post.caption}</p>}</a>)}</div></div></section>}

    <section className="relative z-10 mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-24" id="contact"><div className="overflow-hidden rounded-[1.7rem] border border-blue-200/12 bg-gradient-to-br from-[#111d31] to-[#090f1a]"><div className="grid lg:grid-cols-[1.05fr_.95fr]"><div className="p-6 sm:p-9 lg:p-12"><p className="text-sm font-semibold uppercase tracking-[.18em] text-blue-300">Visit & connect</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.045em] sm:text-4xl">Find Manisa and stay connected.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-white/8 bg-black/10 p-5"><MapPin className="text-blue-300" size={20}/><p className="mt-4 text-sm font-semibold">Address</p><p className="mt-1 text-sm leading-6 text-slate-500">{business.address}</p></div><div className="rounded-xl border border-white/8 bg-black/10 p-5"><Instagram className="text-blue-300" size={20}/><p className="mt-4 text-sm font-semibold">Instagram</p>{business.instagram ? <a className="mt-1 inline-flex items-center gap-1 text-sm text-blue-300 hover:text-blue-200" href={business.instagram} rel="noreferrer" target="_blank">Open studio profile<ExternalLink size={13}/></a> : <p className="mt-1 text-sm text-slate-500">Ask the studio for its latest social profile.</p>}</div></div></div><div className="border-t border-white/8 bg-black/10 p-6 sm:p-9 lg:border-l lg:border-t-0 lg:p-12"><ShieldCheck className="text-blue-300" size={28}/><h3 className="mt-5 text-2xl font-semibold tracking-[-.035em]">Private studio management</h3><p className="mt-3 max-w-md text-sm leading-7 text-slate-400">Authorized staff manage scheduling, customers, services, Gallery selections, and reporting in a secured workspace.</p><Link className="button mt-8" href={staffHref}>{staffLabel}<ArrowRight size={15}/></Link></div></div></div></section>

    <footer className="relative z-10 border-t border-white/8"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-slate-600 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-10"><p>© {new Date().getFullYear()} Manisa. All rights reserved.</p><div className="flex items-center gap-5"><a className="hover:text-slate-300" href="#services">Services</a>{featuredPhotos.length > 0 && <a className="hover:text-slate-300" href="#gallery">Gallery</a>}<Link className="hover:text-slate-300" href={staffHref}>{staffLabel}</Link></div></div></footer>
  </main>;
}
