import Link from "next/link";
import { ArrowDown, ArrowUp, Banknote, CreditCard, Landmark, Plus, Save, Trash2, WalletCards } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { BulkSelection, SelectableItem } from "@/components/bulk-selection";
import { FinancialCharts } from "@/components/financial-charts";
import { ConfirmActionForm } from "@/components/confirm-action-form";
import { requireUser } from "@/lib/auth";
import { customerName, formatMoney } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { createPaymentMethod, movePaymentMethod, movePaymentMethodToTrash, updatePaymentMethod } from "@/server/actions/finance";
import { bulkMoveToTrash } from "@/server/actions/trash";

const iconOptions = ["banknote", "credit-card", "landmark", "wallet"] as const;
const iconMap = { banknote: Banknote, "credit-card": CreditCard, landmark: Landmark, wallet: WalletCards };
const presets = [["7", "7 days"], ["30", "30 days"], ["90", "90 days"], ["ytd", "YTD"], ["all", "All time"], ["custom", "Custom"]] as const;

function startFor(preset: string) {
  const now = new Date();
  if (preset === "all") return new Date(0);
  if (preset === "ytd") return new Date(now.getFullYear(), 0, 1);
  const days = ["7", "30", "90"].includes(preset) ? Number(preset) : 30;
  return new Date(now.getTime() - (days - 1) * 86_400_000);
}

export default async function FinancialPage({ searchParams }: { searchParams: Promise<{ preset?: string; from?: string; to?: string; methodId?: string; paymentStatus?: string }> }) {
  const [query, user] = await Promise.all([searchParams, requireUser()]);
  const preset = ["7", "30", "90", "ytd", "all", "custom"].includes(query.preset || "") ? query.preset! : "30";
  const validDate = (value?: string) => Boolean(value && /^\d{4}-\d{2}-\d{2}$/.test(value));
  const paymentStatus = ["PAID", "UNPAID", "PARTIALLY_PAID"].includes(query.paymentStatus || "") ? query.paymentStatus as "PAID" | "UNPAID" | "PARTIALLY_PAID" : undefined;
  const start = preset === "custom" && validDate(query.from) ? new Date(`${query.from}T00:00:00`) : startFor(preset);
  const end = preset === "custom" && validDate(query.to) ? new Date(`${query.to}T23:59:59.999`) : new Date();
  const [appointments, methods, transactions] = await Promise.all([
    prisma.appointment.findMany({ where: { deletedAt: null, status: "COMPLETED", completedAt: { gte: start, lte: end } }, include: { payments: { where: { voidedAt: null } } } }),
    prisma.paymentMethod.findMany({ where: { deletedAt: null }, orderBy: [{ position: "asc" }, { name: "asc" }] }),
    prisma.appointmentPayment.findMany({ where: { voidedAt: null, paidAt: { gte: start, lte: end }, ...(query.methodId ? { paymentMethodId: query.methodId } : {}), appointment: { deletedAt: null, ...(paymentStatus ? { paymentStatus } : {}) } }, include: { appointment: { include: { customer: true } } }, orderBy: { paidAt: "desc" }, take: 100 }),
  ]);
  const currency = user.settings?.currency || "CAD";
  const finalRevenue = appointments.reduce((sum, item) => sum + Number(item.finalPrice || 0), 0);
  const collected = transactions.reduce((sum, item) => sum + Number(item.amount), 0);
  const outstanding = appointments.filter((item) => !item.paymentReconciliationRequired).reduce((sum, item) => sum + Math.max(0, Number(item.finalPrice || 0) - item.payments.reduce((paid, payment) => paid + Number(payment.amount), 0)), 0);
  const methodTotals = new Map<string, number>();
  transactions.forEach((item) => methodTotals.set(item.methodNameSnapshot, (methodTotals.get(item.methodNameSnapshot) || 0) + Number(item.amount)));
  const collectionBuckets = new Map<string, number>(); transactions.forEach((item) => { const name = new Intl.DateTimeFormat("en-CA", { month: "short", day: "numeric" }).format(item.paidAt); collectionBuckets.set(name, (collectionBuckets.get(name) || 0) + Number(item.amount)); });
  const outstandingAppointments = appointments.filter((item) => item.paymentStatus !== "PAID");
  return <><PageHeading backHref="/settings" title="Financial"/>
    <nav className="mb-4 flex gap-2 overflow-x-auto" data-horizontal-scroll>{presets.map(([value, label]) => <Link className={`filter-chip ${preset === value ? "active" : ""}`} href={`/settings/financial?preset=${value}`} key={value}>{label}</Link>)}</nav>{preset === "custom" && <form className="panel mb-4 grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto]"><input name="preset" type="hidden" value="custom"/><div><label className="label">From</label><input className="field" name="from" type="date" defaultValue={query.from}/></div><div><label className="label">To</label><input className="field" name="to" type="date" defaultValue={query.to}/></div><button className="button self-end">Apply</button></form>}
    <section className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><article className="stat"><p className="text-xs text-slate-500">Final revenue</p><p className="mt-2 text-xl font-semibold">{formatMoney(finalRevenue, currency)}</p></article><article className="stat"><p className="text-xs text-slate-500">Collected</p><p className="mt-2 text-xl font-semibold text-emerald-300">{formatMoney(collected, currency)}</p></article><article className="stat"><p className="text-xs text-slate-500">Outstanding</p><p className="mt-2 text-xl font-semibold text-amber-200">{formatMoney(outstanding, currency)}</p></article><article className="stat"><p className="text-xs text-slate-500">Average collection</p><p className="mt-2 text-xl font-semibold">{formatMoney(transactions.length ? collected / transactions.length : 0, currency)}</p></article><article className="stat"><p className="text-xs text-slate-500">Paid visits</p><p className="mt-2 text-xl font-semibold">{appointments.filter((item) => item.paymentStatus === "PAID").length}</p></article><article className="stat"><p className="text-xs text-slate-500">Partial visits</p><p className="mt-2 text-xl font-semibold">{appointments.filter((item) => item.paymentStatus === "PARTIALLY_PAID").length}</p></article><article className="stat"><p className="text-xs text-slate-500">Unpaid visits</p><p className="mt-2 text-xl font-semibold">{appointments.filter((item) => item.paymentStatus === "UNPAID").length}</p></article><article className="stat"><p className="text-xs text-slate-500">Needs review</p><p className="mt-2 text-xl font-semibold">{appointments.filter((item) => item.paymentReconciliationRequired).length}</p></article></section>
    <FinancialCharts collections={[...collectionBuckets].map(([name, amount]) => ({ name, amount }))} currency={currency} methods={[...methodTotals].map(([name, amount]) => ({ name, amount }))}/>
    <form className="panel mt-5 grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto]"><input name="preset" type="hidden" value={preset}/><select className="field" name="methodId" defaultValue={query.methodId || ""}><option value="">All methods</option>{methods.map((method) => <option key={method.id} value={method.id}>{method.name}</option>)}</select><select className="field" name="paymentStatus" defaultValue={query.paymentStatus || ""}><option value="">All statuses</option><option value="PAID">Paid</option><option value="PARTIALLY_PAID">Partially paid</option><option value="UNPAID">Unpaid</option></select><button className="button">Apply</button></form>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-semibold">Recent payments</h2></div><div className="divide-y divide-white/8">{transactions.slice(0, 20).map((payment) => <Link className="flex items-center justify-between gap-3 p-4 hover:bg-white/[.025]" href={`/appointments/${payment.appointmentId}#payments`} key={payment.id}><span className="min-w-0"><span className="block truncate text-sm font-medium">{customerName(payment.appointment.customer)}</span><span className="text-xs text-slate-500">{payment.methodNameSnapshot}</span></span><span className="text-sm font-semibold text-emerald-300">{formatMoney(payment.amount, payment.appointment.currency)}</span></Link>)}</div></section><section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-semibold">Outstanding appointments</h2></div><div className="divide-y divide-white/8">{outstandingAppointments.slice(0, 20).map((appointment) => <Link className="flex items-center justify-between gap-3 p-4 hover:bg-white/[.025]" href={`/appointments/${appointment.id}#payments`} key={appointment.id}><span className="truncate text-sm">{appointment.serviceNameSnapshot}</span><span className="text-xs text-amber-200">{appointment.paymentReconciliationRequired ? "Needs review" : appointment.paymentStatus.replaceAll("_", " ")}</span></Link>)}</div></section></div>
    <BulkSelection action={bulkMoveToTrash.bind(null, "paymentMethod")} allIds={methods.map((method) => method.id)} locale={user.settings?.locale || "en"}><section className="panel mt-5 overflow-hidden"><div className="panel-header"><h2 className="font-semibold">Payment methods</h2></div><div className="divide-y divide-white/8">{methods.map((method, index) => { const Icon = iconMap[method.icon as keyof typeof iconMap] || WalletCards; return <SelectableItem id={method.id} key={method.id}><form action={updatePaymentMethod.bind(null, method.id)} className="grid gap-2 p-4 sm:grid-cols-[auto_1fr_10rem_auto_auto] sm:items-center"><Icon className="text-blue-300" size={18}/><input className="field" name="name" defaultValue={method.name}/><select className="field" name="icon" defaultValue={method.icon}>{iconOptions.map((icon) => <option key={icon}>{icon}</option>)}</select><label className="flex items-center gap-2 text-xs"><input name="active" type="checkbox" defaultChecked={method.active}/>Active</label><div className="flex gap-2"><button aria-label="Save method" className="icon-button" title="Save"><Save size={15}/></button><button aria-label="Move up" className="icon-button" disabled={index === 0} formAction={movePaymentMethod.bind(null, method.id, "up")} title="Move up"><ArrowUp size={14}/></button><button aria-label="Move down" className="icon-button" disabled={index === methods.length - 1} formAction={movePaymentMethod.bind(null, method.id, "down")} title="Move down"><ArrowDown size={14}/></button><ConfirmActionForm action={movePaymentMethodToTrash.bind(null, method.id)} className="icon-button border-rose-400/20 text-rose-300" message={user.settings?.locale === "fa" ? `${method.name} به سطل زباله منتقل شود؟` : `Move ${method.name} to Trash?`} title="Move to Trash"><Trash2 size={15}/></ConfirmActionForm></div></form></SelectableItem>; })}</div><form action={createPaymentMethod} className="grid gap-2 border-t border-white/8 p-4 sm:grid-cols-[1fr_10rem_auto_auto]"><input className="field" name="name" placeholder="New payment method" required/><select className="field" name="icon" defaultValue="wallet">{iconOptions.map((icon) => <option key={icon}>{icon}</option>)}</select><label className="flex items-center gap-2 text-xs"><input name="active" type="checkbox" defaultChecked/>Active</label><button aria-label="Add method" className="icon-button" title="Add"><Plus size={16}/></button></form></section></BulkSelection>
  </>;
}
