import Link from "next/link";
import { CalendarDays, ChartNoAxesCombined, Clock3, Contact, Gauge, LogOut, Scissors, Settings2 } from "lucide-react";
import type { AppLocale } from "@/lib/i18n";
import { getMessages } from "@/lib/i18n";
import { logout } from "@/server/actions/auth";
const items = [["/dashboard","dashboard",Gauge],["/appointments","appointments",CalendarDays],["/customers","customers",Contact],["/services","services",Scissors],["/calendar","calendar",CalendarDays],["/reports","reports",ChartNoAxesCombined],["/working-hours","workingHours",Clock3],["/settings","settings",Settings2]] as const;
export function AppShell({ children, locale, userName }: { children: React.ReactNode; locale: AppLocale; userName: string }) {
  const t = getMessages(locale);
  return <div className="app-background min-h-screen md:grid md:grid-cols-[15.5rem_1fr]" dir={locale === "fa" ? "rtl" : "ltr"}>
    <aside className="sticky top-0 hidden h-screen border-e border-white/8 bg-[#090d13]/95 p-4 md:flex md:flex-col"><Link href="/dashboard" className="flex h-14 items-center gap-3 px-2"><span className="flex size-9 items-center justify-center rounded-xl bg-teal-300 text-sm font-bold text-slate-950">M</span><span className="font-semibold">Manisa</span></Link><nav className="mt-6 space-y-1">{items.map(([href,key,Icon]) => <Link key={href} href={href} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-400 transition hover:bg-white/[0.05] hover:text-white"><Icon size={18}/>{t[key]}</Link>)}</nav><div className="mt-auto border-t border-white/8 pt-4"><p className="truncate px-3 text-sm font-medium text-slate-300">{userName}</p><form action={logout}><button className="mt-2 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-500 hover:bg-white/[0.05] hover:text-white"><LogOut size={17}/>{t.signOut}</button></form></div></aside>
    <div className="min-w-0"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-white/8 bg-[#080b10]/85 px-5 backdrop-blur-xl md:px-8"><Link href="/dashboard" className="flex items-center gap-2 font-semibold md:hidden"><span className="flex size-8 items-center justify-center rounded-lg bg-teal-300 text-xs font-bold text-slate-950">M</span>Manisa</Link><div className="hidden text-sm text-slate-500 md:block">{new Intl.DateTimeFormat(locale === "fa" ? "fa-IR" : "en-CA", { dateStyle: "full" }).format(new Date())}</div><Link href="/appointments/new" className="button h-9 min-h-9">+ {t.newAppointment}</Link></header><main className="mx-auto max-w-[94rem] p-5 md:p-8 lg:p-10">{children}</main></div>
    <nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-white/10 bg-[#090d13]/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur-xl md:hidden">{items.slice(0,5).map(([href,key,Icon]) => <Link key={href} href={href} className="flex flex-col items-center gap-1 py-1 text-[10px] text-slate-500"><Icon size={19}/><span>{t[key]}</span></Link>)}</nav>
  </div>;
}
