"use client";
import Link from "next/link";
import { useState } from "react";
type Option = { id: string; name: string };
type ServiceOption = Option & { duration: number; price: string };
type AppointmentValue = { customerId: string; serviceId: string; startAt: string; expectedDurationMinutes: number; expectedPrice: string; notes?: string | null };
export function AppointmentForm({ action, customers, services, appointment, initialCustomerId }: { action: (data: FormData) => void | Promise<void>; customers: Option[]; services: ServiceOption[]; appointment?: AppointmentValue; initialCustomerId?: string }) {
  const initialService = services.find((service) => service.id === appointment?.serviceId) || services[0];
  const [duration,setDuration] = useState(appointment?.expectedDurationMinutes || initialService?.duration || 60); const [price,setPrice] = useState(appointment?.expectedPrice || initialService?.price || "0.00");
  return <form action={action} className="panel max-w-3xl p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><div className="mb-2 flex items-center justify-between"><label className="label mb-0" htmlFor="customerId">Customer *</label><Link href="/customers/new" className="text-xs text-teal-300">Create customer</Link></div><select className="field" id="customerId" name="customerId" defaultValue={appointment?.customerId || initialCustomerId || ""} required><option value="" disabled>Select a customer</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="sm:col-span-2"><label className="label" htmlFor="serviceId">Service *</label><select className="field" id="serviceId" name="serviceId" defaultValue={appointment?.serviceId || initialService?.id || ""} required onChange={(event) => { const service = services.find((item) => item.id === event.target.value); if (service) { setDuration(service.duration); setPrice(service.price); } }}>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><label className="label" htmlFor="startAt">Date and time *</label><input className="field" id="startAt" name="startAt" type="datetime-local" defaultValue={appointment?.startAt} required/></div><div><label className="label" htmlFor="expectedDurationMinutes">Expected duration</label><input className="field" id="expectedDurationMinutes" name="expectedDurationMinutes" type="number" min="5" step="5" value={duration} onChange={(event) => setDuration(Number(event.target.value))} required/></div><div><label className="label" htmlFor="expectedPrice">Expected price</label><input className="field" id="expectedPrice" name="expectedPrice" inputMode="decimal" value={price} onChange={(event) => setPrice(event.target.value)} required/></div><div className="sm:col-span-2"><label className="label" htmlFor="notes">Appointment notes</label><textarea className="field min-h-28" id="notes" name="notes" defaultValue={appointment?.notes || ""}/></div></div><div className="mt-7 flex justify-end gap-3"><Link className="button-secondary" href="/appointments">Cancel</Link><button className="button">Save appointment</button></div></form>;
}
