"use client";

import { useActionState, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, ChevronDown, Clock3, LoaderCircle, Scissors, Sparkles, UserRound } from "lucide-react";
import { bookingSubmissionFields } from "@/lib/public-booking";
import { publicContentDirection, type PublicLocale } from "@/lib/public-site";
import { submitPublicBooking, type PublicBookingResult } from "@/server/actions/public-booking";

type PublicService = { id: string; name: string; duration: number; price: string; currency: string; categoryId: string; categoryName: string };
type Availability = { state: "idle" | "loading" | "ready" | "error"; slots: string[]; message?: string };

const copy = {
  en: {
    steps: ["Services", "Date & time", "Your details", "Review"], services: "Choose your services", date: "Choose a date and time", otherDate: "Or choose another date", times: "Available times", checking: "Checking the calendar…", chooseDate: "Select a date to see available times.", unavailable: "Availability could not be loaded.", noTimes: "No times remain on this date.", details: "Tell us how to reach you", name: "Your name *", phone: "Phone number *", email: "Email · optional", updates: "Appointment updates", noUpdates: "No updates for now", sms: "Text message", notes: "Notes · optional", notesPlaceholder: "Anything the studio should know?", consent: "I agree to receive updates about this appointment through", review: "Review your request", summaryServices: "Services", summaryDate: "Date & time", summaryVisit: "Estimated visit", summaryContact: "Contact", approval: "I reviewed this request and understand the studio will approve or decline it.", back: "Back", next: "Next", sending: "Sending…", request: "Send request", received: "Request sent", another: "Make another request", progress: "Booking progress", minutes: "min",
  },
  fa: {
    steps: ["خدمات", "تاریخ و زمان", "اطلاعات شما", "بازبینی"], services: "خدمات خود را انتخاب کنید", date: "تاریخ و زمان را انتخاب کنید", otherDate: "یا تاریخ دیگری انتخاب کنید", times: "زمان‌های موجود", checking: "در حال بررسی تقویم…", chooseDate: "برای دیدن زمان‌های موجود یک تاریخ انتخاب کنید.", unavailable: "زمان‌های موجود بارگیری نشدند.", noTimes: "در این تاریخ زمانی باقی نمانده است.", details: "راه ارتباط با شما", name: "نام شما *", phone: "شماره تلفن *", email: "ایمیل · اختیاری", updates: "اطلاع‌رسانی قرار", noUpdates: "فعلاً بدون اطلاع‌رسانی", sms: "پیامک", notes: "یادداشت · اختیاری", notesPlaceholder: "نکته‌ای هست که استودیو باید بداند؟", consent: "موافقم به‌روزرسانی‌های این قرار را دریافت کنم از طریق", review: "درخواست خود را بازبینی کنید", summaryServices: "خدمات", summaryDate: "تاریخ و زمان", summaryVisit: "زمان و هزینه تقریبی", summaryContact: "راه ارتباط", approval: "این درخواست را بررسی کردم و می‌دانم استودیو آن را تأیید یا رد خواهد کرد.", back: "قبلی", next: "بعدی", sending: "در حال ارسال…", request: "ارسال درخواست", received: "درخواست ارسال شد", another: "ثبت درخواست دیگر", progress: "مراحل رزرو", minutes: "دقیقه",
  },
} as const;

function dateRange(todayKey: string, locale: PublicLocale, count = 28) {
  const start = new Date(`${todayKey}T12:00:00Z`);
  const intlLocale = locale === "fa" ? "fa-IR-u-ca-gregory-nu-latn" : "en-CA";
  return Array.from({ length: count }, (_, index) => { const date = new Date(start); date.setUTCDate(start.getUTCDate() + index); return { key: date.toISOString().slice(0, 10), weekday: new Intl.DateTimeFormat(intlLocale, { weekday: "short", timeZone: "UTC" }).format(date), day: date.getUTCDate(), month: new Intl.DateTimeFormat(intlLocale, { month: "short", timeZone: "UTC" }).format(date), weekdayNumber: date.getUTCDay() }; });
}

function money(value: string, currency: string, locale: PublicLocale) { return new Intl.NumberFormat(locale === "fa" ? "fa-IR-u-nu-latn" : "en-CA", { style: "currency", currency }).format(Number(value)); }

export function PublicBookingForm({ services, todayKey, enabledWeekdays, locale }: { services: PublicService[]; todayKey: string; enabledWeekdays: number[]; locale: PublicLocale }) {
  const t = copy[locale];
  const [step, setStep] = useState(0);
  const [serviceIds, setServiceIds] = useState<string[]>([]);
  const [openCategoryId, setOpenCategoryId] = useState<string | null>(() => services[0]?.categoryId || null);
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");
  const [availability, setAvailability] = useState<Availability>({ state: "idle", slots: [] });
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [email, setEmail] = useState("");
  const [notes, setNotes] = useState("");
  const [preference, setPreference] = useState("NONE");
  const [consent, setConsent] = useState(false);
  const [result, action, pending] = useActionState<PublicBookingResult, FormData>(submitPublicBooking, null);
  const dates = useMemo(() => dateRange(todayKey, locale), [todayKey, locale]);
  const selectedServices = services.filter((service) => serviceIds.includes(service.id));
  const duration = selectedServices.reduce((sum, service) => sum + service.duration, 0);
  const total = selectedServices.reduce((sum, service) => sum + Number(service.price), 0);
  const groups = Array.from(new Map(services.map((service) => [service.categoryId, service.categoryName]))).map(([id, categoryName]) => ({ id, categoryName, services: services.filter((service) => service.categoryId === id) }));
  const canContinue = step === 0 ? serviceIds.length > 0 : step === 1 ? Boolean(date && time && availability.state === "ready" && availability.slots.includes(time)) : step === 2 ? Boolean(name.trim().length >= 2 && phone.trim().length >= 7 && (preference !== "EMAIL" || email.trim()) && (preference === "NONE" || consent)) : true;
  const submissionFields = bookingSubmissionFields({ name, phone, email, notes, notificationPreference: preference, consent });

  useEffect(() => {
    if (!date || !serviceIds.length) return;
    const controller = new AbortController();
    const timer = window.setTimeout(async () => {
      setAvailability({ state: "loading", slots: [] });
      try {
        const response = await fetch(`/api/public/availability?date=${encodeURIComponent(date)}&serviceIds=${encodeURIComponent(serviceIds.join(","))}`, { cache: "no-store", signal: controller.signal });
        const data = await response.json() as { available?: boolean; slots?: string[]; error?: string };
        if (!response.ok || !data.available) setAvailability({ state: "error", slots: [], message: data.error || t.unavailable });
        else setAvailability({ state: "ready", slots: data.slots || [], message: data.slots?.length ? undefined : t.noTimes });
      } catch { if (!controller.signal.aborted) setAvailability({ state: "error", slots: [], message: t.unavailable }); }
    }, 180);
    return () => { window.clearTimeout(timer); controller.abort(); };
  }, [date, serviceIds, t.noTimes, t.unavailable]);

  if (result?.success) return <section className="public-booking-card p-7 text-center sm:p-10" role="status"><span className="mx-auto flex size-16 items-center justify-center rounded-full bg-[var(--public-accent-soft)] text-[var(--public-accent)]"><CheckCircle2 size={31}/></span><h3 className="mt-5 font-serif text-3xl">{t.received}</h3><p className="mx-auto mt-3 max-w-lg leading-7 text-[var(--public-muted)]">{result.success}</p><button className="public-primary mt-7" onClick={() => window.location.reload()} type="button">{t.another}</button></section>;

  return <form action={action} className="public-booking-card p-4 sm:p-7" dir={locale === "fa" ? "rtl" : "ltr"} onSubmit={(event) => { if (step < 3) { event.preventDefault(); if (canContinue) setStep((value) => value + 1); } else if (!canContinue) event.preventDefault(); }}>
    <ol aria-label={t.progress} className="mb-7 flex min-w-0 items-start">{t.steps.map((label, index) => <li className="relative flex min-w-0 flex-1 flex-col items-center text-center" key={label}>{index > 0 && <span className={`absolute end-1/2 top-3.5 h-0.5 w-full ${index <= step ? "bg-[var(--public-accent)]" : "bg-[var(--public-line)]"}`}/>}<span className={`relative z-10 flex size-7 items-center justify-center rounded-full text-xs font-bold ${index < step ? "bg-[var(--public-button)] text-white" : index === step ? "bg-[var(--public-ink)] text-[var(--public-bg)] ring-4 ring-[var(--public-accent-soft)]" : "bg-[var(--public-soft)] text-[var(--public-muted)]"}`}>{index < step ? <Check size={14}/> : index + 1}</span><span className={`mt-2 max-w-full truncate px-1 text-[10px] sm:text-xs ${index <= step ? "text-[var(--public-ink)]" : "text-[var(--public-muted)]"}`}>{label}</span></li>)}</ol>

    {step === 0 && <section><Heading icon={Sparkles} title={t.services}/><div className="space-y-3">{groups.map((group) => { const selectedCount = group.services.filter((service) => serviceIds.includes(service.id)).length; const open = openCategoryId === group.id; return <section className="overflow-hidden rounded-2xl bg-[var(--public-soft)]" key={group.id}><button aria-expanded={open} className="flex w-full cursor-pointer items-center gap-3 px-4 py-4 text-start" onClick={() => setOpenCategoryId(open ? null : group.id)} type="button"><h4 className="min-w-0 flex-1 truncate text-sm font-bold text-[var(--public-accent)] [unicode-bidi:isolate]" dir={publicContentDirection(group.categoryName)}>{group.categoryName}</h4>{selectedCount > 0 && <span className="rounded-full bg-[var(--public-button)] px-2 py-0.5 text-xs font-bold text-white">{selectedCount}</span>}<ChevronDown className={`shrink-0 text-[var(--public-muted)] transition ${open ? "rotate-180" : ""}`} size={17}/></button>{open && <div className="grid gap-2 border-t border-[var(--public-line)] p-3 sm:grid-cols-2">{group.services.map((service) => { const selected = serviceIds.includes(service.id); const serviceDirection = publicContentDirection(service.name); return <button aria-pressed={selected} className={`flex min-w-0 items-center gap-3 rounded-xl p-3.5 text-start transition ${selected ? "bg-[var(--public-ink)] text-[var(--public-bg)] shadow-lg" : "bg-[var(--public-card)] text-[var(--public-ink)] hover:brightness-95"}`} dir={serviceDirection} key={service.id} onClick={() => { setServiceIds((ids) => ids.includes(service.id) ? ids.filter((id) => id !== service.id) : [...ids, service.id]); setTime(""); setAvailability({ state: "idle", slots: [] }); }} type="button"><Scissors className="shrink-0" size={17}/><span className="min-w-0 flex-1"><span className="block truncate font-semibold [unicode-bidi:isolate]">{service.name}</span><span className={`mt-1 block text-xs ${selected ? "opacity-65" : "text-[var(--public-muted)]"}`} dir="ltr">{service.duration} {t.minutes} · {money(service.price, service.currency, locale)}</span></span><span className={`flex size-5 shrink-0 items-center justify-center rounded-full ${selected ? "bg-[var(--public-bg)] text-[var(--public-ink)]" : "bg-[var(--public-line)] text-transparent"}`}><Check size={13}/></span></button>; })}</div>}</section>; })}</div></section>}

    {step === 1 && <section><Heading icon={CalendarDays} title={t.date}/><div className="grid grid-cols-7 gap-1.5 sm:gap-2">{dates.map((item) => { const disabled = !enabledWeekdays.includes(item.weekdayNumber); return <button aria-pressed={date === item.key} className={`min-w-0 rounded-xl px-1 py-2.5 text-center transition ${date === item.key ? "bg-[var(--public-ink)] text-[var(--public-bg)]" : disabled ? "cursor-not-allowed bg-[var(--public-soft)] opacity-35" : "bg-[var(--public-soft)] text-[var(--public-ink)] hover:brightness-95"}`} disabled={disabled} key={item.key} onClick={() => { setDate(item.key); setTime(""); setAvailability({ state: "idle", slots: [] }); }} type="button"><span className="block truncate text-[9px] uppercase">{item.weekday}</span><span className="mt-1 block text-sm font-bold">{item.day}</span><span className="block truncate text-[9px]">{item.month}</span></button>; })}</div><label className="mt-4 block text-xs font-semibold text-[var(--public-muted)]" htmlFor="public-booking-date">{t.otherDate}</label><input className="public-field mt-1" id="public-booking-date" max={dates.at(-1)?.key} min={todayKey} onChange={(event) => { setDate(event.target.value); setTime(""); setAvailability({ state: "idle", slots: [] }); }} type="date" value={date}/><div className="mt-5"><p className="mb-2 flex items-center gap-2 text-sm font-semibold"><Clock3 size={16}/>{t.times}</p>{availability.state === "loading" ? <p className="flex items-center gap-2 py-4 text-sm text-[var(--public-muted)]"><LoaderCircle className="animate-spin" size={17}/>{t.checking}</p> : availability.slots.length ? <div className="grid grid-cols-3 gap-2 sm:grid-cols-4">{availability.slots.map((slot) => <button aria-pressed={time === slot} className={`rounded-xl px-2 py-2.5 text-sm font-semibold transition ${time === slot ? "bg-[var(--public-button)] text-white" : "bg-[var(--public-soft)] hover:brightness-95"}`} key={slot} onClick={() => setTime(slot)} type="button">{new Intl.DateTimeFormat(locale === "fa" ? "fa-IR-u-nu-latn" : "en-CA", { hour: "numeric", minute: "2-digit" }).format(new Date(`2020-01-01T${slot}:00`))}</button>)}</div> : <p className="rounded-xl bg-[var(--public-soft)] p-4 text-sm text-[var(--public-muted)]">{availability.message || t.chooseDate}</p>}</div></section>}

    {step === 2 && <section><Heading icon={UserRound} title={t.details}/><div className="grid gap-4 sm:grid-cols-2"><Field label={t.name}><input className="public-field" dir="auto" maxLength={120} name="name" onChange={(event) => setName(event.target.value)} required value={name}/></Field><Field label={t.phone}><input className="public-field" dir="ltr" inputMode="tel" maxLength={50} name="phone" onChange={(event) => setPhone(event.target.value)} required value={phone}/></Field><Field label={t.email}><input className="public-field" dir="ltr" maxLength={160} name="email" onChange={(event) => setEmail(event.target.value)} type="email" value={email}/></Field><Field label={t.updates}><select className="public-field" name="notificationPreference" onChange={(event) => { setPreference(event.target.value); if (event.target.value === "NONE") setConsent(false); }} value={preference}><option value="NONE">{t.noUpdates}</option><option value="WHATSAPP">WhatsApp</option><option value="SMS">{t.sms}</option><option value="EMAIL">Email</option></select></Field><Field className="sm:col-span-2" label={t.notes}><textarea className="public-field min-h-24 resize-y" dir="auto" maxLength={1000} name="notes" onChange={(event) => setNotes(event.target.value)} placeholder={t.notesPlaceholder} value={notes}/></Field>{preference !== "NONE" && <label className="sm:col-span-2 flex cursor-pointer items-start gap-3 rounded-xl bg-[var(--public-accent-soft)] p-4 text-sm leading-6"><input checked={consent} className="mt-1 accent-[var(--public-accent)]" name="consent" onChange={(event) => setConsent(event.target.checked)} type="checkbox"/>{t.consent} {preference === "WHATSAPP" ? "WhatsApp" : preference === "SMS" ? t.sms : "Email"}.</label>}<input aria-label="Leave this field empty" autoComplete="off" className="hidden" name="website" tabIndex={-1}/></div></section>}

    {step === 3 && <section><Heading icon={CheckCircle2} title={t.review}/><div className="grid gap-4 rounded-2xl bg-[var(--public-soft)] p-4 sm:grid-cols-2"><Summary label={t.summaryServices} value={selectedServices.map((service) => service.name).join(" · ")}/><Summary label={t.summaryDate} value={`${date} · ${time}`}/><Summary label={t.summaryVisit} value={`${duration} ${t.minutes} · ${money(total.toFixed(2), selectedServices[0]?.currency || "CAD", locale)}`}/><Summary label={t.summaryContact} value={`${name} · ${phone}`}/></div>{result?.error && <p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-600" role="alert">{result.error}</p>}</section>}

    {serviceIds.map((id) => <input key={id} name="serviceIds" type="hidden" value={id}/>)}<input name="date" type="hidden" value={date}/><input name="time" type="hidden" value={time}/><input name="locale" type="hidden" value={locale}/>{Object.entries(submissionFields).map(([fieldName, value]) => <input key={fieldName} name={fieldName} type="hidden" value={value}/>)}
    <div className="mt-7 flex gap-2 border-t border-[var(--public-line)] pt-5">{step > 0 && <button className="public-secondary" onClick={() => setStep((value) => value - 1)} type="button"><ArrowLeft className={locale === "fa" ? "rotate-180" : ""} size={16}/>{t.back}</button>}<button className="public-primary ms-auto" disabled={!canContinue || pending} type={step === 3 ? "submit" : "button"} onClick={step === 3 ? undefined : () => setStep((value) => value + 1)}>{pending ? <><LoaderCircle className="animate-spin" size={16}/>{t.sending}</> : step === 3 ? t.request : <>{t.next}<ArrowRight className={locale === "fa" ? "rotate-180" : ""} size={16}/></>}</button></div>
  </form>;
}

function Heading({ icon: Icon, title }: { icon: typeof Sparkles; title: string }) { return <div className="mb-5 flex items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-[var(--public-accent-soft)] text-[var(--public-accent)]"><Icon size={18}/></span><h3 className="font-serif text-2xl">{title}</h3></div>; }
function Field({ label, className = "", children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={className}><span className="mb-1.5 block text-xs font-semibold text-[var(--public-muted)]">{label}</span>{children}</label>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--public-accent)]">{label}</p><p className="mt-1.5 break-words text-sm font-semibold" dir="auto">{value}</p></div>; }
