"use client";

import Link from "next/link";
import { useState } from "react";
import { CircleHelp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AppLocale } from "@/lib/i18n";

type TrendPoint = { name: string; revenue: number; visits: number; hours: number };
type ServicePoint = { id: string; name: string; revenue: number; visits: number; hours: number };
type ValuePoint = { name: string; value: number };
type WorkPoint = { name: string; hours: number; revenue: number; visits: number };

const colors = ["#60A5FA", "#A78BFA", "#22D3EE", "#34D399", "#F59E0B", "#FB7185"];
const axis = { fontSize: 10, fill: "#64748b" };

function money(value: number) { return new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD", maximumFractionDigits: 0 }).format(value); }
function metricValue(metric: "revenue" | "visits" | "hours", value: number) { return metric === "revenue" ? money(value) : metric === "hours" ? `${value.toFixed(1)}h` : String(value); }

function Switch({ value, onChange }: { value: "revenue" | "visits" | "hours"; onChange: (value: "revenue" | "visits" | "hours") => void }) {
  return <div className="metric-switch" data-swipe-lock>{(["revenue", "visits", "hours"] as const).map((metric) => <button aria-pressed={value === metric} className={value === metric ? "active" : ""} key={metric} onClick={() => onChange(metric)} type="button">{metric}</button>)}</div>;
}

function ChartPanel({ title, subtitle, action, children }: { title: string; subtitle: string; action?: React.ReactNode; children: React.ReactNode }) {
  return <section className="panel chart-panel min-w-0 overflow-hidden" data-swipe-lock><div className="panel-header"><div className="flex min-w-0 items-center gap-1.5"><h2 className="truncate text-sm font-semibold text-white">{title}</h2><details className="group relative"><summary aria-label="Help" className="flex size-6 cursor-pointer list-none items-center justify-center text-slate-600 hover:text-blue-300"><CircleHelp size={13}/></summary><p className="absolute start-0 top-7 z-20 w-56 rounded-lg border border-blue-300/15 bg-[#101927] p-2.5 text-[11px] leading-4 text-slate-300 shadow-xl">{subtitle}</p></details></div>{action}</div><div className="p-3 sm:p-5">{children}</div></section>;
}

export function ReportCharts({ trend, previousTrend, services, outcomes, payments, busiestDays, busiestHours, monthlyHours, queryString }: { trend: TrendPoint[]; previousTrend: TrendPoint[]; services: ServicePoint[]; outcomes: ValuePoint[]; payments: ValuePoint[]; busiestDays: ValuePoint[]; busiestHours: ValuePoint[]; monthlyHours: WorkPoint[]; queryString: string; currency: string; locale: AppLocale }) {
  const [trendMetric, setTrendMetric] = useState<"revenue" | "visits" | "hours">("revenue");
  const [serviceMetric, setServiceMetric] = useState<"revenue" | "visits" | "hours">("revenue");
  const trendData = trend.map((point, index) => ({ ...point, previous: previousTrend[index]?.[trendMetric] || 0 }));
  const empty = <div className="empty min-h-56">Finalize appointments to populate this chart.</div>;
  return <div className="grid gap-4 xl:grid-cols-2">
    <ChartPanel title="Performance over time" subtitle="Current period with preceding-period comparison" action={<Switch value={trendMetric} onChange={setTrendMetric}/>}>{trendData.length ? <div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData} margin={{ left: -18, right: 8, top: 10, bottom: 0 }}><defs><linearGradient id="report-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#60A5FA" stopOpacity={0.32}/><stop offset="100%" stopColor="#60A5FA" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.08)" vertical={false}/><XAxis dataKey="name" tick={axis} tickLine={false} axisLine={false} minTickGap={22}/><YAxis tick={axis} tickLine={false} axisLine={false}/><Tooltip contentStyle={{ background: "#0b1320", border: "1px solid rgba(96,165,250,.28)", borderRadius: 12 }} formatter={(value) => metricValue(trendMetric, Number(value))}/><Legend wrapperStyle={{ fontSize: 11 }}/><Area dataKey={trendMetric} name="Current" stroke="#60A5FA" strokeWidth={2.2} fill="url(#report-area)" activeDot={{ r: 5 }}/><Area dataKey="previous" name="Previous" stroke="#64748B" strokeDasharray="5 5" fill="transparent"/></AreaChart></ResponsiveContainer></div> : empty}</ChartPanel>
    <ChartPanel title="Service performance" subtitle="Tap a service below to filter detailed records" action={<Switch value={serviceMetric} onChange={setServiceMetric}/>}>{services.length ? <><div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={services.slice(0, 8)} layout="vertical" margin={{ left: 4, right: 16 }}><CartesianGrid stroke="rgba(148,163,184,.08)" horizontal={false}/><XAxis type="number" tick={axis} tickLine={false} axisLine={false}/><YAxis dataKey="name" type="category" width={92} tick={axis} tickLine={false} axisLine={false}/><Tooltip cursor={{ fill: "rgba(96,165,250,.06)" }} contentStyle={{ background: "#0b1320", border: "1px solid rgba(96,165,250,.28)", borderRadius: 12 }} formatter={(value) => metricValue(serviceMetric, Number(value))}/><Bar dataKey={serviceMetric} fill="#60A5FA" radius={[0, 7, 7, 0]}/></BarChart></ResponsiveContainer></div><div className="mt-3 flex flex-wrap gap-2">{services.slice(0, 8).map((service) => <Link className="chart-filter-link" href={`/report?${queryString}${queryString ? "&" : ""}serviceId=${service.id}#records`} key={service.id}>{service.name}</Link>)}</div></> : empty}</ChartPanel>
    <div className="grid min-w-0 grid-cols-2 gap-2 xl:col-span-2 sm:gap-4">
      <ChartPanel title="Appointment outcomes" subtitle="Distribution of every appointment state">{outcomes.length ? <div className="h-52 sm:h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={outcomes} dataKey="value" nameKey="name" innerRadius="45%" outerRadius="72%" paddingAngle={3}>{outcomes.map((point, index) => <Cell fill={colors[index % colors.length]} key={point.name}/>)}</Pie><Tooltip contentStyle={{ background: "#0b1320", border: "1px solid rgba(96,165,250,.28)", borderRadius: 12 }}/><Legend wrapperStyle={{ fontSize: 9 }}/></PieChart></ResponsiveContainer></div> : empty}</ChartPanel>
      <ChartPanel title="Payment distribution" subtitle="Finalized revenue by payment status">{payments.length ? <div className="h-52 sm:h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={payments} dataKey="value" nameKey="name" innerRadius="45%" outerRadius="72%" paddingAngle={3}>{payments.map((point, index) => <Cell fill={colors[(index + 2) % colors.length]} key={point.name}/>)}</Pie><Tooltip formatter={(value) => money(Number(value))} contentStyle={{ background: "#0b1320", border: "1px solid rgba(96,165,250,.28)", borderRadius: 12 }}/><Legend wrapperStyle={{ fontSize: 9 }}/></PieChart></ResponsiveContainer></div> : empty}</ChartPanel>
    </div>
    <ChartPanel title="Busiest periods" subtitle="Finalized visits by weekday and start time">{busiestDays.length || busiestHours.length ? <div className="grid gap-4 sm:grid-cols-2"><div><p className="mb-2 text-xs font-medium text-slate-400">Weekdays</p><div className="h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={busiestDays}><XAxis dataKey="name" tick={axis} tickLine={false} axisLine={false}/><YAxis tick={axis} tickLine={false} axisLine={false}/><Tooltip contentStyle={{ background: "#0b1320", border: "1px solid rgba(96,165,250,.28)", borderRadius: 12 }}/><Bar dataKey="value" fill="#A78BFA" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div><div><p className="mb-2 text-xs font-medium text-slate-400">Start times</p><div className="h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={busiestHours.slice(0,8)}><XAxis dataKey="name" tick={axis} tickLine={false} axisLine={false}/><YAxis tick={axis} tickLine={false} axisLine={false}/><Tooltip contentStyle={{ background: "#0b1320", border: "1px solid rgba(96,165,250,.28)", borderRadius: 12 }}/><Bar dataKey="value" fill="#22D3EE" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div></div> : empty}</ChartPanel>
    <ChartPanel title="Monthly working hours" subtitle="Actual finalized time, income, and visit count">{monthlyHours.length ? <div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyHours} margin={{ left: -18, right: 8 }}><CartesianGrid stroke="rgba(148,163,184,.08)" vertical={false}/><XAxis dataKey="name" tick={axis} tickLine={false} axisLine={false}/><YAxis tick={axis} tickLine={false} axisLine={false}/><Tooltip contentStyle={{ background: "#0b1320", border: "1px solid rgba(96,165,250,.28)", borderRadius: 12 }}/><Legend wrapperStyle={{ fontSize: 10 }}/><Bar dataKey="hours" name="Hours" fill="#60A5FA" radius={[5,5,0,0]}/><Bar dataKey="visits" name="Visits" fill="#34D399" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div> : empty}</ChartPanel>
  </div>;
}
