CREATE TYPE "Role" AS ENUM ('ADMIN');
CREATE TYPE "Locale" AS ENUM ('en', 'fa');
CREATE TYPE "Theme" AS ENUM ('DARK', 'LIGHT', 'SYSTEM');
CREATE TYPE "AppointmentStatus" AS ENUM ('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
CREATE TYPE "PaymentStatus" AS ENUM ('UNPAID', 'PAID', 'PARTIALLY_PAID');
CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "name" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'ADMIN', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Settings" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "businessName" TEXT NOT NULL DEFAULT 'Manisa', "locale" "Locale" NOT NULL DEFAULT 'en', "theme" "Theme" NOT NULL DEFAULT 'DARK', "currency" VARCHAR(3) NOT NULL DEFAULT 'CAD', "timezone" TEXT NOT NULL DEFAULT 'America/Toronto', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Settings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Customer" ("id" TEXT NOT NULL, "firstName" TEXT NOT NULL, "lastName" TEXT, "displayName" TEXT, "phone" TEXT, "email" TEXT, "address" TEXT, "notes" TEXT, "preferredLanguage" "Locale" NOT NULL DEFAULT 'en', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Customer_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Service" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "defaultDurationMinutes" INTEGER NOT NULL, "defaultPrice" DECIMAL(12,2) NOT NULL, "currency" VARCHAR(3) NOT NULL DEFAULT 'CAD', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Service_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Appointment" ("id" TEXT NOT NULL, "customerId" TEXT NOT NULL, "serviceId" TEXT NOT NULL, "serviceNameSnapshot" TEXT NOT NULL, "startAt" TIMESTAMPTZ(3) NOT NULL, "expectedDurationMinutes" INTEGER NOT NULL, "actualDurationMinutes" INTEGER, "status" "AppointmentStatus" NOT NULL DEFAULT 'SCHEDULED', "expectedPrice" DECIMAL(12,2) NOT NULL, "finalPrice" DECIMAL(12,2), "currency" VARCHAR(3) NOT NULL DEFAULT 'CAD', "paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'UNPAID', "notes" TEXT, "completionNotes" TEXT, "calendarEventId" TEXT, "calendarSyncError" TEXT, "completedAt" TIMESTAMPTZ(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Appointment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Settings_userId_key" ON "Settings"("userId");
CREATE INDEX "Customer_firstName_lastName_idx" ON "Customer"("firstName", "lastName");
CREATE INDEX "Customer_phone_idx" ON "Customer"("phone");
CREATE INDEX "Customer_email_idx" ON "Customer"("email");
CREATE INDEX "Customer_active_idx" ON "Customer"("active");
CREATE INDEX "Service_name_idx" ON "Service"("name");
CREATE INDEX "Service_active_idx" ON "Service"("active");
CREATE INDEX "Appointment_startAt_idx" ON "Appointment"("startAt");
CREATE INDEX "Appointment_customerId_startAt_idx" ON "Appointment"("customerId", "startAt");
CREATE INDEX "Appointment_serviceId_startAt_idx" ON "Appointment"("serviceId", "startAt");
CREATE INDEX "Appointment_status_startAt_idx" ON "Appointment"("status", "startAt");
CREATE INDEX "Appointment_paymentStatus_idx" ON "Appointment"("paymentStatus");
ALTER TABLE "Settings" ADD CONSTRAINT "Settings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
