import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { customerName, formatMoney } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { formatBusinessDate } from "@/lib/time";
import { archiveCustomer } from "@/server/actions/customers";
export default async function CustomerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const customer = await prisma.customer.findUnique({ where: { id }, include: { appointments: { orderBy: { startAt: "desc" } } } }); if (!customer) notFound();
  const completed = customer.appointments.filter((item) => item.status === "COMPLETED"); const revenue = completed.reduce((sum,item) => sum + Number(item.finalPrice || 0),0); const upcoming = customer.appointments.filter((item) => item.startAt > new Date() && ["SCHEDULED","CONFIRMED"].includes(item.status));
  return <><PageHeading title={customerName(customer)} description={customer.active ? "Active customer" : "Archived customer"} actions={<><Link className="button" href={`/appointments/new?customerId=${id}`}>+ Appointment</Link><Link className="button-secondary" href={`/customers/${id}/edit`}>Edit</Link></>}/><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><div className="space-y-5"><section className="panel p-5 sm:p-6"><h2 className="font-medium">Contact</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-600">Phone</dt><dd className="mt-1 text-slate-300">{customer.phone || "—"}</dd></div><div><dt className="text-slate-600">Email</dt><dd className="mt-1 text-slate-300">{customer.email || "—"}</dd></div><div><dt className="text-slate-600">Address</dt><dd className="mt-1 text-slate-300">{customer.address || "—"}</dd></div><div><dt className="text-slate-600">Notes</dt><dd className="mt-1 whitespace-pre-wrap text-slate-300">{customer.notes || "—"}</dd></div></dl></section><section className="grid grid-cols-2 gap-3"><div className="stat"><p className="text-xs text-slate-500">Appointments</p><p className="mt-3 text-2xl font-semibold">{customer.appointments.length}</p></div><div className="stat"><p className="text-xs text-slate-500">Completed</p><p className="mt-3 text-2xl font-semibold">{completed.length}</p></div><div className="stat"><p className="text-xs text-slate-500">Revenue</p><p className="mt-3 text-xl font-semibold">{formatMoney(revenue)}</p></div><div className="stat"><p className="text-xs text-slate-500">Upcoming</p><p className="mt-3 text-2xl font-semibold">{upcoming.length}</p></div></section>{customer.active && <form action={archiveCustomer.bind(null,id)}><button className="button-danger w-full">Archive customer</button></form>}</div><section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-medium">Appointment history</h2></div>{customer.appointments.length ? <div className="divide-y divide-white/8">{customer.appointments.map((item) => <Link key={item.id} href={`/appointments/${item.id}`} className="flex flex-col gap-2 px-5 py-4 hover:bg-white/[0.025] sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{item.serviceNameSnapshot}</p><p className="mt-1 text-sm text-slate-500">{formatBusinessDate(item.startAt,"en")}</p></div><div className="flex items-center gap-2"><StatusBadge status={item.status}/>{item.finalPrice && <span className="text-sm text-slate-400">{formatMoney(item.finalPrice,item.currency)}</span>}</div></Link>)}</div> : <div className="empty">No appointments yet.</div>}</section></div></>;
}
