import { subMonths } from "date-fns";
import { AnalyticsCharts } from "@/components/analytics-charts";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { formatMoney } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { parseBusinessDateTime } from "@/lib/time";
export default async function ReportsPage({ searchParams }: { searchParams:Promise<{from?:string;to?:string;serviceId?:string;status?:string;paymentStatus?:string}> }) {
  const filters=await searchParams; const from=filters.from&&/^\d{4}-\d{2}-\d{2}$/.test(filters.from)?parseBusinessDateTime(`${filters.from}T00:00`):subMonths(new Date(),6); const to=filters.to&&/^\d{4}-\d{2}-\d{2}$/.test(filters.to)?parseBusinessDateTime(`${filters.to}T23:59`):new Date();
  const allowedStatuses=["SCHEDULED","CONFIRMED","COMPLETED","CANCELLED","NO_SHOW"] as const; const allowedPayments=["UNPAID","PAID","PARTIALLY_PAID"] as const; const status=allowedStatuses.find((value)=>value===filters.status); const paymentStatus=allowedPayments.find((value)=>value===filters.paymentStatus);
  const where={ startAt:{gte:from,lte:to}, ...(filters.serviceId?{serviceId:filters.serviceId}:{}), ...(status?{status}:{}), ...(paymentStatus?{paymentStatus}:{}) };
  const [appointments,services,newCustomers]=await Promise.all([prisma.appointment.findMany({where,orderBy:{startAt:"desc"}}),prisma.service.findMany({where:{active:true}}),prisma.customer.count({where:{createdAt:{gte:from,lte:to}}})]);
  const completed=appointments.filter((a)=>a.status==="COMPLETED"); const revenue=completed.reduce((s,a)=>s+Number(a.finalPrice||0),0); const minutes=completed.reduce((s,a)=>s+(a.actualDurationMinutes||0),0); const serviceMap=new Map<string,number>(); completed.forEach(a=>serviceMap.set(a.serviceNameSnapshot,(serviceMap.get(a.serviceNameSnapshot)||0)+Number(a.finalPrice||0))); const serviceData=[...serviceMap].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value); const monthData=new Map<string,number>(); completed.forEach(a=>{const name=new Intl.DateTimeFormat("en",{month:"short",year:"2-digit"}).format(a.completedAt||a.startAt);monthData.set(name,(monthData.get(name)||0)+Number(a.finalPrice||0));});
  return <><PageHeading title="Reports" description="Filter real business records and review financial and operational performance."/><form className="panel mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><div><label className="label" htmlFor="from">From</label><input className="field" id="from" name="from" type="date" defaultValue={filters.from}/></div><div><label className="label" htmlFor="to">To</label><input className="field" id="to" name="to" type="date" defaultValue={filters.to}/></div><div><label className="label" htmlFor="serviceId">Service</label><select className="field" id="serviceId" name="serviceId" defaultValue={filters.serviceId}><option value="">All services</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="label" htmlFor="status">Status</label><select className="field" id="status" name="status" defaultValue={filters.status}><option value="">All statuses</option><option>COMPLETED</option><option>CANCELLED</option><option>NO_SHOW</option><option>SCHEDULED</option></select></div><div className="flex items-end"><button className="button w-full">Apply filters</button></div></form><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><article className="stat"><p className="text-xs text-slate-500">Revenue</p><p className="mt-3 text-2xl font-semibold">{formatMoney(revenue)}</p></article><article className="stat"><p className="text-xs text-slate-500">Completed</p><p className="mt-3 text-2xl font-semibold">{completed.length}</p></article><article className="stat"><p className="text-xs text-slate-500">New customers</p><p className="mt-3 text-2xl font-semibold">{newCustomers}</p></article><article className="stat"><p className="text-xs text-slate-500">Working hours</p><p className="mt-3 text-2xl font-semibold">{(minutes/60).toFixed(1)}h</p></article><article className="stat"><p className="text-xs text-slate-500">Hourly income</p><p className="mt-3 text-2xl font-semibold">{formatMoney(minutes?revenue/(minutes/60):0)}</p></article></div><div className="mt-5"><AnalyticsCharts revenue={[...monthData].map(([name,value])=>({name,value}))} services={serviceData}/></div><section className="panel mt-5 overflow-hidden"><div className="panel-header"><h2 className="font-medium">Report records</h2><span className="text-xs text-slate-500">{appointments.length} results</span></div><div className="divide-y divide-white/8">{appointments.slice(0,50).map(a=><div key={a.id} className="flex items-center justify-between gap-4 px-5 py-3"><div><p className="text-sm font-medium">{a.serviceNameSnapshot}</p><p className="mt-1 text-xs text-slate-600">{new Intl.DateTimeFormat("en-CA",{dateStyle:"medium"}).format(a.startAt)}</p></div><div className="flex items-center gap-3"><StatusBadge status={a.status}/><span className="text-sm text-slate-300">{formatMoney(a.finalPrice||a.expectedPrice,a.currency)}</span></div></div>)}</div></section></>;
}
