import Link from "next/link";
import { Search } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { customerName } from "@/lib/format";
import { prisma } from "@/lib/prisma";
export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const q = (await searchParams).q?.trim() || "";
  const customers = await prisma.customer.findMany({ where: { active: true, ...(q ? { OR: [{ firstName: { contains: q, mode: "insensitive" } }, { lastName: { contains: q, mode: "insensitive" } }, { displayName: { contains: q, mode: "insensitive" } }, { phone: { contains: q } }, { email: { contains: q, mode: "insensitive" } }] } : {}) }, include: { _count: { select: { appointments: true } } }, orderBy: { updatedAt: "desc" }, take: 100 });
  return <><PageHeading title="Customers" description="Customer relationships and appointment history." actions={<Link className="button" href="/customers/new">+ New customer</Link>}/><form className="panel mb-4 flex items-center gap-3 p-3"><Search className="ms-1 text-slate-500" size={18}/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600" name="q" defaultValue={q} placeholder="Search names, phone, or email…"/><button className="button-secondary h-9 min-h-9" type="submit">Search</button></form><section className="panel overflow-hidden">{customers.length ? <div className="divide-y divide-white/8">{customers.map((customer) => <Link href={`/customers/${customer.id}`} key={customer.id} className="grid gap-2 px-5 py-4 transition hover:bg-white/[0.025] sm:grid-cols-[1.4fr_1fr_1fr_auto] sm:items-center sm:px-6"><div><p className="font-medium">{customerName(customer)}</p><p className="mt-1 text-xs text-slate-500">{customer.preferredLanguage === "fa" ? "فارسی" : "English"}</p></div><p className="text-sm text-slate-400">{customer.phone || "No phone"}</p><p className="truncate text-sm text-slate-500">{customer.email || "No email"}</p><span className="text-xs text-slate-600">{customer._count.appointments} appointments</span></Link>)}</div> : <div className="empty"><p>No customers found.</p><Link className="mt-4 text-sm text-teal-300" href="/customers/new">Create the first customer</Link></div>}</section></>;
}
