import Link from "next/link";
import { PageHeading } from "@/components/page-heading";
import { formatMoney } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { toggleService } from "@/server/actions/services";
export default async function ServicesPage() {
  const services = await prisma.service.findMany({ include: { appointments: { where: { status: "COMPLETED" }, select: { finalPrice: true, actualDurationMinutes: true } } }, orderBy: [{ active: "desc" }, { name: "asc" }] });
  return <><PageHeading title="Services" description="Pricing, duration defaults, and historical performance." actions={<Link className="button" href="/services/new">+ New service</Link>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => { const revenue = service.appointments.reduce((sum,a) => sum + Number(a.finalPrice || 0),0); const minutes = service.appointments.reduce((sum,a) => sum + (a.actualDurationMinutes || 0),0); return <article className={`panel p-5 sm:p-6 ${service.active ? "" : "opacity-60"}`} key={service.id}><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium text-white">{service.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{service.description || "No description"}</p></div><span className={`badge ${service.active ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : "border-white/10 text-slate-500"}`}>{service.active ? "active" : "inactive"}</span></div><div className="mt-6 grid grid-cols-3 gap-3 border-y border-white/8 py-4 text-center"><div><p className="text-lg font-semibold">{service.defaultDurationMinutes}m</p><p className="mt-1 text-[11px] text-slate-600">duration</p></div><div><p className="text-lg font-semibold">{formatMoney(service.defaultPrice,service.currency)}</p><p className="mt-1 text-[11px] text-slate-600">default</p></div><div><p className="text-lg font-semibold">{service.appointments.length}</p><p className="mt-1 text-[11px] text-slate-600">completed</p></div></div><div className="mt-4 flex items-center justify-between"><div><p className="text-xs text-slate-600">Revenue · hourly</p><p className="mt-1 text-sm text-slate-300">{formatMoney(revenue,service.currency)} · {formatMoney(minutes ? revenue/(minutes/60) : 0,service.currency)}</p></div><div className="flex gap-2"><Link className="button-secondary h-9 min-h-9 px-3" href={`/services/${service.id}/edit`}>Edit</Link><form action={toggleService.bind(null,service.id,!service.active)}><button className="button-secondary h-9 min-h-9 px-3">{service.active ? "Disable" : "Enable"}</button></form></div></div></article>; })}</div>{!services.length && <div className="panel empty">No services yet.</div>}</>;
}
